import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Link2, RefreshCw, Search, Unlink } from 'lucide-react'
import { fetchWithAuth } from '../api'

type Order = { liquidstock_supplier_order_id:string; liquidstock_order_id:string; liquidstock_venue_id:string; venue_name_snapshot?:string; supplier_name_snapshot:string; status:string; sent_at?:string; received_at?:string; reconciliation_id?:string; reconciliation_status?:string; fattura_id?:number }
type Invoice = { id:number; numero_documento:string; data_documento:string; totale_imponibile:number; already_associated_to?:string; suggestion_score:number; suggestion_reasons:string[] }
type Item = { id:number; liquidstock_item_id?:string; riga_fattura_id?:number; product_id?:number; order_product_name?:string; invoice_product_description?:string; ordered_package_note?:string; ordered_quantity?:number; received_quantity?:number; invoiced_quantity?:number; ordered_unit?:string; invoiced_unit?:string; expected_unit_price?:number; expected_price_source?:string; invoiced_unit_price?:number; quantity_delta?:number; price_delta?:number; disputed_amount?:number; match_status:string; anomaly_type?:string; match_method?:string; match_confidence:number; match_reason?:string; candidate_evidence?:{fallback_candidates?:Array<{liquidstock_item_id:string;product_id?:number;score:number}>} }
type Detail = { id:string; status:string; reconciliation_version:number; fattura_id?:number; invoice_number?:string; invoice_date?:string; supplier_name?:string; venue_name?:string; matching_confidence:number; anomalies:Array<{id:number;anomaly_type:string;workflow_status:string;disputed_amount?:number}>; items:Item[] }

const panel: React.CSSProperties = { background:'var(--bg-glass)', border:'1px solid var(--border-glass)', borderRadius:12, padding:18 }
const badge = (value:string) => <span style={{fontSize:11,padding:'4px 8px',borderRadius:999,background:value.includes('match')?'rgba(34,197,94,.14)':'rgba(245,158,11,.14)',color:value.includes('match')?'#4ade80':'#fbbf24'}}>{value}</span>

export default function OrderReconciliations(){
  const [orders,setOrders]=useState<Order[]>([]); const [selected,setSelected]=useState<Order|null>(null)
  const [detail,setDetail]=useState<Detail|null>(null); const [invoices,setInvoices]=useState<Invoice[]>([])
  const [venue,setVenue]=useState(''); const [supplier,setSupplier]=useState(''); const [status,setStatus]=useState(''); const [dateFrom,setDateFrom]=useState(''); const [dateTo,setDateTo]=useState('')
  const [mappingVenue,setMappingVenue]=useState(''); const [locationId,setLocationId]=useState('')
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const load=async()=>{ setBusy(true);setError('');try{const q=new URLSearchParams();if(venue)q.set('venue_id',venue);if(supplier)q.set('supplier_id',supplier);if(status)q.set('status',status);if(dateFrom)q.set('date_from',dateFrom);if(dateTo)q.set('date_to',dateTo);const rows=await fetchWithAuth(`/reconciliations/orders?${q}`);setOrders(rows)}catch(e){setError(e instanceof Error?e.message:'Caricamento non riuscito')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  const open=async(order:Order)=>{setSelected(order);setError('');setInvoices([]);try{if(order.reconciliation_id)setDetail(await fetchWithAuth(`/reconciliations/${order.reconciliation_id}`));else setDetail(null);setInvoices(await fetchWithAuth(`/reconciliations/orders/${order.liquidstock_supplier_order_id}/invoice-candidates`))}catch(e){setError(e instanceof Error?e.message:'Dati non disponibili')}}
  const act=async(label:string,fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setMessage('');try{const value=await fn();if(value&&typeof value==='object'&&'items' in value)setDetail(value as Detail);setMessage(label);await load()}catch(e){setError(e instanceof Error?e.message:'Operazione non riuscita')}finally{setBusy(false)}}
  const associate=(invoice:Invoice,allowReassociate=false)=>selected&&act('Fattura associata manualmente.',async()=>fetchWithAuth(`/reconciliations/orders/${selected.liquidstock_supplier_order_id}/invoice`,{method:'POST',body:JSON.stringify({fattura_id:invoice.id,allow_reassociate:allowReassociate,price_tolerance_absolute:.01,price_tolerance_percent:1})}))
  const disputed=useMemo(()=>detail?.items.reduce((sum,item)=>sum+Number(item.disputed_amount||0),0)||0,[detail])
  return <div style={{display:'flex',flexDirection:'column',gap:18}} data-testid="order-reconciliations">
    <div style={panel}><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>
      <input placeholder="Venue UUID" value={venue} onChange={e=>setVenue(e.target.value)} />
      <input placeholder="Fornitore ID" value={supplier} onChange={e=>setSupplier(e.target.value)} />
      <input type="date" aria-label="Data dal" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} />
      <input type="date" aria-label="Data al" value={dateTo} onChange={e=>setDateTo(e.target.value)} />
      <select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tutti gli stati</option>{['awaiting_invoice','matching','partially_matched','matched','anomalies_found','reviewed','closed'].map(v=><option key={v}>{v}</option>)}</select>
      <button className="btn btn-primary" onClick={()=>void load()} disabled={busy}><Search size={15}/> Filtra</button>
    </div></div>
    <div style={panel}><strong>Mappatura venue esplicita</strong><p style={{color:'var(--text-secondary)',fontSize:12}}>Necessaria per bloccare associazioni cross-venue; non viene dedotta dal nome.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input placeholder="LiquidStock venue UUID" value={mappingVenue} onChange={e=>setMappingVenue(e.target.value)}/><input placeholder="Price location ID" value={locationId} onChange={e=>setLocationId(e.target.value)}/><button className="btn" onClick={()=>act('Mappatura venue salvata.',()=>fetchWithAuth('/reconciliations/venue-mappings',{method:'POST',body:JSON.stringify({liquidstock_venue_id:mappingVenue,location_id:Number(locationId)})}))}>Salva mappatura</button></div></div>
    {error&&<div style={{...panel,borderColor:'rgba(239,68,68,.4)',color:'#f87171'}}><AlertTriangle size={16}/> {error}</div>}{message&&<div style={{...panel,color:'#4ade80'}}><CheckCircle2 size={16}/> {message}</div>}
    <div style={{display:'grid',gridTemplateColumns:'minmax(280px,1fr) minmax(0,2fr)',gap:18}}>
      <div style={{...panel,display:'flex',flexDirection:'column',gap:8}}><h3>Ordini LiquidStock</h3>{orders.map(order=><button key={order.liquidstock_supplier_order_id} onClick={()=>void open(order)} style={{textAlign:'left',padding:12,borderRadius:9,border:selected?.liquidstock_supplier_order_id===order.liquidstock_supplier_order_id?'1px solid var(--accent-blue)':'1px solid var(--border-glass)',background:'rgba(255,255,255,.025)',color:'white'}}><strong>{order.supplier_name_snapshot}</strong><div style={{fontSize:11,color:'var(--text-secondary)',marginTop:5}}>{order.venue_name_snapshot||order.liquidstock_venue_id}</div><div style={{marginTop:6}}>{badge(order.reconciliation_status||'awaiting_invoice')}</div></button>)}</div>
      <div style={{display:'flex',flexDirection:'column',gap:14}}>{selected&&(!detail||!detail.fattura_id)&&<div style={panel}><h3>Fatture candidate</h3><p style={{fontSize:12,color:'var(--text-secondary)'}}>Suggerimenti soltanto: il collegamento richiede conferma.</p>{invoices.map(invoice=><div key={invoice.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 0',borderBottom:'1px solid var(--border-glass)'}}><div><strong>{invoice.numero_documento}</strong> · {invoice.data_documento}<div style={{fontSize:11,color:'var(--text-secondary)'}}>{invoice.suggestion_reasons.join(' · ')} · confidence {Number(invoice.suggestion_score).toFixed(2)}</div></div><button className="btn" disabled={busy} onClick={()=>{if(!invoice.already_associated_to||window.confirm('La fattura è già associata. Confermi la riassegnazione esplicita?'))void associate(invoice,!!invoice.already_associated_to)}}><Link2 size={14}/> {invoice.already_associated_to?'Riassegna':'Associa'}</button></div>)}</div>}
      {detail&&<><div style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3>{detail.supplier_name} · {detail.invoice_number||'Nessuna fattura'}</h3><div>{badge(detail.status)} <span style={{fontSize:12,color:'var(--text-secondary)'}}>confidence {Number(detail.matching_confidence).toFixed(2)} · contestato € {disputed.toFixed(2)}</span></div></div><div style={{display:'flex',gap:8}}>{detail.invoice_number&&<button className="btn" onClick={()=>act('Fattura scollegata.',()=>fetchWithAuth(`/reconciliations/${detail.id}/invoice`,{method:'DELETE'}))}><Unlink size={14}/> Scollega</button>}<button className="btn btn-primary" onClick={()=>act('Matching completato.',()=>fetchWithAuth(`/reconciliations/${detail.id}/match`,{method:'POST'}))}><RefreshCw size={14}/> Matching</button><button className="btn" onClick={()=>act('Riconciliazione chiusa.',()=>fetchWithAuth(`/reconciliations/${detail.id}/close`,{method:'POST',body:'{}'}))}>Chiudi</button></div></div></div>
      <div style={{...panel,overflowX:'auto'}}><h3>Ordine / ricezione / fattura</h3><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th>Prodotto ordine</th><th>Descrizione fattura</th><th>Ordine</th><th>Ricevuto</th><th>Fatturato</th><th>Unità / confezione</th><th>Prezzo atteso</th><th>Prezzo fattura</th><th>Esito</th><th>Azioni</th></tr></thead><tbody>{detail.items.map(item=><tr key={item.id}><td>{item.order_product_name||'—'}</td><td>{item.invoice_product_description||'—'}</td><td>{item.ordered_quantity??'—'}</td><td>{item.received_quantity??'—'}</td><td>{item.invoiced_quantity??'—'}</td><td>{item.ordered_unit||'—'} / {item.invoiced_unit||'—'}<small style={{display:'block'}}>{item.ordered_package_note||'nessuna nota confezione'}</small></td><td>{item.expected_unit_price??'—'}<small style={{display:'block'}}>{item.expected_price_source||'nessuna fonte'}</small></td><td>{item.invoiced_unit_price??'—'}</td><td>{badge(item.match_status)}<small style={{display:'block'}}>{item.match_method} · {Number(item.match_confidence).toFixed(2)}<br/>{item.match_reason}</small></td><td><div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{item.match_status==='ambiguous'&&item.candidate_evidence?.fallback_candidates?.map(c=><button className="btn" key={c.liquidstock_item_id} onClick={()=>act('Match confermato.',()=>fetchWithAuth(`/reconciliations/${detail.id}/items/${item.id}/resolve`,{method:'POST',body:JSON.stringify({action:'confirm',liquidstock_item_id:c.liquidstock_item_id,product_id:c.product_id})}))}>Conferma {c.score}</button>)}<button className="btn" onClick={()=>act('Riga ignorata.',()=>fetchWithAuth(`/reconciliations/${detail.id}/items/${item.id}/resolve`,{method:'POST',body:JSON.stringify({action:'ignore'})}))}>Ignora</button>{item.anomaly_type&&<button className="btn" onClick={()=>act('Anomalia creata.',()=>fetchWithAuth(`/reconciliations/${detail.id}/items/${item.id}/resolve`,{method:'POST',body:JSON.stringify({action:'create_anomaly'})}))}>Crea anomalia</button>}</div></td></tr>)}</tbody></table></div></>}
      </div>
    </div>
  </div>
}
