"""add_ordini_tables

Revision ID: d17bcbd219e5
Revises: f7aa8d06f5de
Create Date: 2026-05-19 16:43:45.935748+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17bcbd219e5'
down_revision: Union[str, None] = 'f7aa8d06f5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordini',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fornitore_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('data_ordine', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spesa_totale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordini_fornitore_id'), 'ordini', ['fornitore_id'], unique=False)
    op.create_index(op.f('ix_ordini_location_id'), 'ordini', ['location_id'], unique=False)
    op.create_table('righe_ordine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordine_id', sa.Integer(), nullable=False),
    sa.Column('sku_interno', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prezzo_pattuito', sa.Numeric(precision=12, scale=4), nullable=False, comment='Prezzo concordato o miglior spot di riferimento'),
    sa.Column('prezzo_inserito', sa.Numeric(precision=12, scale=4), nullable=False, comment='Prezzo effettivamente inserito dal buyer'),
    sa.Column('stato_ottimizzazione', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ordine_id'], ['ordini.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_righe_ordine_ordine_id'), 'righe_ordine', ['ordine_id'], unique=False)
    op.create_index(op.f('ix_righe_ordine_sku_interno'), 'righe_ordine', ['sku_interno'], unique=False)
    op.drop_index('listino_master_descrizione_trgm_idx', table_name='listino_master', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('listino_master_descrizione_trgm_idx', 'listino_master', ['descrizione'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_righe_ordine_sku_interno'), table_name='righe_ordine')
    op.drop_index(op.f('ix_righe_ordine_ordine_id'), table_name='righe_ordine')
    op.drop_table('righe_ordine')
    op.drop_index(op.f('ix_ordini_location_id'), table_name='ordini')
    op.drop_index(op.f('ix_ordini_fornitore_id'), table_name='ordini')
    op.drop_table('ordini')
    # ### end Alembic commands ###
