"""initial_with_manual_upload

Revision ID: d04728aebaad
Revises: 
Create Date: 2026-05-05 15:59:21.836183+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd04728aebaad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stato', postgresql.ENUM('in_elaborazione', 'completato', 'completato_con_errori', name='stato_batch', create_type=False), nullable=False),
    sa.Column('file_totali', sa.Integer(), nullable=False),
    sa.Column('file_elaborati', sa.Integer(), nullable=False),
    sa.Column('gia_presenti', sa.Integer(), nullable=False),
    sa.Column('errori_formato', sa.Integer(), nullable=False),
    sa.Column('anomalie_generate', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('xml_raw', sa.Column('source', postgresql.ENUM('webhook', 'upload_manuale', name='source_ingestion', create_type=False), nullable=False, server_default='webhook'))
    op.add_column('xml_raw', sa.Column('upload_batch_id', sa.String(length=36), nullable=True))
    op.add_column('xml_raw', sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_xml_raw_upload_batch_id'), 'xml_raw', ['upload_batch_id'], unique=False)
    op.create_foreign_key(None, 'xml_raw', 'utenti', ['uploaded_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'xml_raw', 'upload_batches', ['upload_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xml_raw', type_='foreignkey')
    op.drop_constraint(None, 'xml_raw', type_='foreignkey')
    op.drop_index(op.f('ix_xml_raw_upload_batch_id'), table_name='xml_raw')
    op.drop_column('xml_raw', 'uploaded_by_user_id')
    op.drop_column('xml_raw', 'upload_batch_id')
    op.drop_column('xml_raw', 'source')
    op.drop_table('upload_batches')
    # ### end Alembic commands ###
