"""add_product_identity_layer

Revision ID: df624f0e7865
Revises: 65951ca80c0b
Create Date: 2026-06-30 17:02:32.624943+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df624f0e7865'
down_revision: Union[str, None] = '65951ca80c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_equivalence_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('comparison_unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('unit_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('container_type', sa.String(length=50), nullable=True),
    sa.Column('comparison_unit', sa.String(length=50), nullable=False),
    sa.Column('is_commodity', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_equivalence_group_items',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['product_equivalence_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'product_id')
    )
    op.create_table('supplier_product_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('raw_description', sa.String(length=255), nullable=False),
    sa.Column('normalized_description', sa.String(length=255), nullable=False),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['fornitori.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'supplier_code', name='uq_supplier_product_aliases_code')
    )
    op.create_index(op.f('ix_supplier_product_aliases_ean'), 'supplier_product_aliases', ['ean'], unique=False)
    op.create_index(op.f('ix_supplier_product_aliases_normalized_description'), 'supplier_product_aliases', ['normalized_description'], unique=False)
    op.create_index(op.f('ix_supplier_product_aliases_product_id'), 'supplier_product_aliases', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_product_aliases_supplier_code'), 'supplier_product_aliases', ['supplier_code'], unique=False)
    op.create_index(op.f('ix_supplier_product_aliases_supplier_id'), 'supplier_product_aliases', ['supplier_id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['righe_fattura.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_invoice_line_id'), 'match_candidates', ['invoice_line_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_product_id'), 'match_candidates', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_candidates_product_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_invoice_line_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_supplier_product_aliases_supplier_id'), table_name='supplier_product_aliases')
    op.drop_index(op.f('ix_supplier_product_aliases_supplier_code'), table_name='supplier_product_aliases')
    op.drop_index(op.f('ix_supplier_product_aliases_product_id'), table_name='supplier_product_aliases')
    op.drop_index(op.f('ix_supplier_product_aliases_normalized_description'), table_name='supplier_product_aliases')
    op.drop_index(op.f('ix_supplier_product_aliases_ean'), table_name='supplier_product_aliases')
    op.drop_table('supplier_product_aliases')
    op.drop_table('product_equivalence_group_items')
    op.drop_table('products')
    op.drop_table('product_equivalence_groups')
    # ### end Alembic commands ###
