"""add_sku_interno_to_products

Revision ID: 00b691c2bad9
Revises: df624f0e7865
Create Date: 2026-06-30 17:04:16.586378+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b691c2bad9'
down_revision: Union[str, None] = 'df624f0e7865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku_interno', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_sku_interno'), 'products', ['sku_interno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku_interno'), table_name='products')
    op.drop_column('products', 'sku_interno')
    # ### end Alembic commands ###
