"""add_skus_esclusi

Revision ID: 65951ca80c0b
Revises: d17bcbd219e5
Create Date: 2026-06-29 14:04:44.101351+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65951ca80c0b'
down_revision: Union[str, None] = 'd17bcbd219e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skus_esclusi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_interno', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_esclusi_sku_interno'), 'skus_esclusi', ['sku_interno'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_esclusi_sku_interno'), table_name='skus_esclusi')
    op.drop_table('skus_esclusi')
    # ### end Alembic commands ###
