"""add_uom_and_trgm

Revision ID: f7aa8d06f5de
Revises: e023c8fd38fa
Create Date: 2026-05-19 11:16:51.992695+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aa8d06f5de'
down_revision: Union[str, None] = 'e023c8fd38fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias_prodotti', sa.Column('coefficiente_conversione', sa.Numeric(precision=10, scale=4), server_default='1.0', nullable=False, comment='Fattore conversione quantita/prezzo (es. 6 se cassa da 6pz)'))
    # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE INDEX IF NOT EXISTS listino_master_descrizione_trgm_idx ON listino_master USING gin (descrizione gin_trgm_ops);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias_prodotti', 'coefficiente_conversione')
    # ### end Alembic commands ###
    op.execute("DROP INDEX IF EXISTS listino_master_descrizione_trgm_idx;")
