"""add supplier_product_alias_id to listino_master

Revision ID: 26cfd21178be
Revises: c7d7399e0622
Create Date: 2026-07-09 11:24:20.730653+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cfd21178be'
down_revision: Union[str, None] = 'c7d7399e0622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listino_master', sa.Column('supplier_product_alias_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_listino_master_supplier_product_alias_id'), 'listino_master', ['supplier_product_alias_id'], unique=False)
    op.create_foreign_key(None, 'listino_master', 'supplier_product_aliases', ['supplier_product_alias_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # --- Backfill listino_master with supplier_product_alias_id ---
    bind = op.get_bind()
    
    # 1. Reactivate the two prices for Ferrarelle 50cl x24 and Electa 50cl x24 if they exist
    bind.execute(
        sa.text(
            "UPDATE listino_master SET data_scadenza = NULL WHERE id IN (1115, 1119) "
            "AND fornitore_id = 11"
        )
    )

    # 2. Map duplicate SKUs explicitly
    duplicate_mapping = {
        18: 1115,  # ACQUA FERRARELLE 0,50 X 24 BT PET -> prezzo 4.9178
        19: 1116,  # ACQUA FERRARELLE 0.50 X20 VAR -> prezzo 4.9180
        22: 1119,  # ACQUA ELECTA 50 CL X 24 PET -> prezzo 4.5078
        24: 1121,  # ACQUA ELECTA 50 CL X 20 VAR BIANCA -> prezzo 4.9180
    }
    for alias_id, listino_id in duplicate_mapping.items():
        bind.execute(
            sa.text(
                "UPDATE listino_master SET supplier_product_alias_id = :alias_id "
                "WHERE id = :listino_id AND fornitore_id = 11"
            ),
            dict(alias_id=alias_id, listino_id=listino_id)
        )

    # 3. Associate all other listino records for Eurocarta/Navas
    bind.execute(
        sa.text(
            "UPDATE listino_master lm "
            "SET supplier_product_alias_id = spa.id "
            "FROM supplier_product_aliases spa "
            "JOIN products p ON spa.product_id = p.id "
            "WHERE lm.fornitore_id = spa.supplier_id "
            "AND lm.sku_interno = p.sku_interno "
            "AND lm.supplier_product_alias_id IS NULL "
            "AND lm.fornitore_id IN (10, 11) "
            "AND lm.id NOT IN (1115, 1116, 1119, 1121)"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listino_master', type_='foreignkey')
    op.drop_index(op.f('ix_listino_master_supplier_product_alias_id'), table_name='listino_master')
    op.drop_column('listino_master', 'supplier_product_alias_id')
    # ### end Alembic commands ###
