"""add_approvazioni_prezzo

Revision ID: e023c8fd38fa
Revises: d04728aebaad
Create Date: 2026-05-19 11:09:04.431936+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e023c8fd38fa'
down_revision: Union[str, None] = 'd04728aebaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvazioni_prezzo',
    sa.Column('sku_interno', sa.String(length=100), nullable=False),
    sa.Column('descrizione_orig', sa.Text(), nullable=False),
    sa.Column('mese', sa.String(length=7), nullable=False, comment='Formato YYYY-MM'),
    sa.Column('prezzo_approvato', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stato', sa.String(length=50), server_default='APPROVATO', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sku_interno', 'descrizione_orig', 'mese')
    )
    op.create_index(op.f('ix_approvazioni_prezzo_sku_interno'), 'approvazioni_prezzo', ['sku_interno'], unique=False)
    op.drop_index('ix_anomalie_riga_fattura_id', table_name='anomalie')
    op.create_index(op.f('ix_anomalie_riga_fattura_id'), 'anomalie', ['riga_fattura_id'], unique=True)
    op.add_column('utenti', sa.Column('refresh_token_version', sa.Integer(), server_default='1', nullable=False, comment='Versione per la rotazione del refresh token'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utenti', 'refresh_token_version')
    op.drop_index(op.f('ix_anomalie_riga_fattura_id'), table_name='anomalie')
    op.create_index('ix_anomalie_riga_fattura_id', 'anomalie', ['riga_fattura_id'], unique=False)
    op.drop_index(op.f('ix_approvazioni_prezzo_sku_interno'), table_name='approvazioni_prezzo')
    op.drop_table('approvazioni_prezzo')
    # ### end Alembic commands ###
