"""add_product_identity_fields

Revision ID: c02b3f8223e0
Revises: 00b691c2bad9
Create Date: 2026-07-06 16:19:34.085787+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02b3f8223e0'
down_revision: Union[str, None] = '00b691c2bad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_candidates', sa.Column('source_type', sa.String(length=50), server_default='invoice_line', nullable=False))
    op.add_column('match_candidates', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('match_candidates', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('match_candidates', sa.Column('raw_description', sa.String(length=255), nullable=True))
    op.add_column('match_candidates', sa.Column('normalized_description', sa.String(length=255), nullable=True))
    op.add_column('match_candidates', sa.Column('block_flag', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('match_candidates', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('match_candidates', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_candidates', sa.Column('resolved_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('match_candidates', 'invoice_line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'match_candidates', 'fornitori', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'match_candidates', 'utenti', ['resolved_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('normalized_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.add_column('supplier_product_aliases', sa.Column('pack_qty', sa.Integer(), nullable=True))
    op.add_column('supplier_product_aliases', sa.Column('volume_ml', sa.Integer(), nullable=True))
    op.add_column('supplier_product_aliases', sa.Column('weight_g', sa.Integer(), nullable=True))
    op.add_column('supplier_product_aliases', sa.Column('container_type', sa.String(length=50), nullable=True))
    op.add_column('supplier_product_aliases', sa.Column('status', sa.String(length=50), server_default='approved', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_product_aliases', 'status')
    op.drop_column('supplier_product_aliases', 'container_type')
    op.drop_column('supplier_product_aliases', 'weight_g')
    op.drop_column('supplier_product_aliases', 'volume_ml')
    op.drop_column('supplier_product_aliases', 'pack_qty')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_column('products', 'normalized_name')
    op.drop_constraint(None, 'match_candidates', type_='foreignkey')
    op.drop_constraint(None, 'match_candidates', type_='foreignkey')
    op.alter_column('match_candidates', 'invoice_line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('match_candidates', 'resolved_by_user_id')
    op.drop_column('match_candidates', 'resolved_at')
    op.drop_column('match_candidates', 'status')
    op.drop_column('match_candidates', 'block_flag')
    op.drop_column('match_candidates', 'normalized_description')
    op.drop_column('match_candidates', 'raw_description')
    op.drop_column('match_candidates', 'supplier_id')
    op.drop_column('match_candidates', 'source_id')
    op.drop_column('match_candidates', 'source_type')
    # ### end Alembic commands ###
